new fullpage("#fullpage", {
    licenseKey: 'gplv3-license',
    lockAnchors: false,
    navigation: false,
    css3: false,
    scrollingSpeed: 800,
    autoScrolling: false,
    fitToSection: false,
    fitToSectionDelay: 700,
    scrollBar: true,
    easing: "easeInOutCubic",
    easingcss3: "ease",
    loopBottom: true,
    loopTop: false,
    loopHorizontal: true,
    continuousVertical: false,
    continuousHorizontal: false,
    scrollHorizontally: false,
    interlockedSlides: false,
    dragAndMove: false,
    offsetSections: false,
    resetSliders: false,
    fadingEffect: false,
    normalScrollElements: "#element1, .element2",
    scrollOverflow: false,
    scrollOverflowMacStyle: false,
    scrollOverflowReset: false,
    touchSensitivity: 15,
    bigSectionsDestination: null,
  });