new fullpage("#fullpage", {
  licenseKey: "gplv3-license",
  navigation: true,
  navigationTooltips: ["home", "about", "menu", "contact"],
  css3: false,
  scrollingSpeed: 800,
  autoScrolling: false,
  fitToSection: false,
  fitToSectionDelay: 700,
  scrollBar: true,
  easingcss3: "ease",
  loopBottom: true,
  loopTop: false,
  fadingEffect: false,
  scrollOverflow: false,
  scrollOverflowMacStyle: false,
  scrollOverflowReset: false,
  touchSensitivity: 15,
});
